import { app } from 'electron';
import electronUpdater from 'electron-updater';
import type { UpdateStatus } from '@shared/ipc';
import { EVENTS } from '@shared/ipc';
import { broadcast } from '../../ipc/broadcast';
import { log } from '../security/logger';

const { autoUpdater } = electronUpdater;

// electron-updater reads the GitHub publish config baked into app-update.yml
// (generated by electron-builder from electron-builder.yml `publish:`), so it
// checks the project's GitHub Releases. The repo/releases must be public for the
// update check to work without a token.

let status: UpdateStatus = { state: 'idle', currentVersion: app.getVersion() };

function set(next: Partial<UpdateStatus>): void {
  status = { ...status, ...next };
  broadcast(EVENTS.updateStatus, status);
}

export function getUpdateStatus(): UpdateStatus {
  return status;
}

/** Wire auto-update and do an initial check. Auto-updates only run in a packaged
 *  build (there's no release to compare against in dev). Downloads happen in the
 *  background; the renderer shows a "restart to update" prompt once ready, and the
 *  update also installs automatically on the next quit. */
export function initAutoUpdate(): void {
  if (!app.isPackaged) {
    log.info('auto-update: skipped (not packaged)');
    return;
  }

  autoUpdater.autoDownload = true;
  autoUpdater.autoInstallOnAppQuit = true;
  autoUpdater.logger = null; // we surface our own status; avoid noisy duplicate logs

  autoUpdater.on('checking-for-update', () => set({ state: 'checking' }));
  autoUpdater.on('update-available', (info) =>
    set({ state: 'available', version: info.version }),
  );
  autoUpdater.on('update-not-available', () => set({ state: 'none', version: undefined }));
  autoUpdater.on('download-progress', (p) =>
    set({ state: 'downloading', percent: Math.round(p.percent) }),
  );
  autoUpdater.on('update-downloaded', (info) => {
    log.info(`auto-update: downloaded v${info.version}`);
    set({ state: 'downloaded', version: info.version });
  });
  autoUpdater.on('error', (e) => {
    log.warn('auto-update: error', e);
    set({ state: 'error', message: e instanceof Error ? e.message : String(e) });
  });

  checkForUpdates();
}

/** Manually trigger a check (e.g. from the Settings "Check for updates" button). */
export function checkForUpdates(): void {
  if (!app.isPackaged) return;
  autoUpdater.checkForUpdates().catch((e) => {
    log.warn('auto-update: checkForUpdates failed', e);
    set({ state: 'error', message: e instanceof Error ? e.message : String(e) });
  });
}

/** Quit and install a downloaded update now (the "Restart to update" button). */
export function installUpdateNow(): void {
  if (status.state !== 'downloaded') return;
  // isSilent=false (show the installer), isForceRunAfter=true (relaunch the app).
  setImmediate(() => autoUpdater.quitAndInstall(false, true));
}
