import { existsSync, mkdirSync, readFileSync, unlinkSync } from 'fs';
import Database from 'better-sqlite3';
import { drizzle, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { join } from 'path';
import { app } from 'electron';
import { paths } from '../env';
import { log } from '../services/security/logger';
import { fixLegacyFkActions } from './fkRebuild';
import * as schema from './schema';

let _db: BetterSQLite3Database<typeof schema> | null = null;
let _sqlite: Database.Database | null = null;

/**
 * Migrations are generated by drizzle-kit under ./drizzle. Depending on how the
 * app is packaged they can land in different spots, so we probe every plausible
 * location and use the first that actually contains the journal — far more robust
 * than assuming one path. In dev they sit at the repo root.
 */
function migrationCandidates(): string[] {
  if (!app.isPackaged) return [join(app.getAppPath(), 'drizzle')];
  return [
    join(process.resourcesPath, 'drizzle'), // extraResources (on disk) — preferred
    join(app.getAppPath(), 'drizzle'), // bundled in app.asar (files)
    join(__dirname, '../../drizzle'), // relative to out/main
  ];
}

/**
 * Snapshot the DB file before applying PENDING migrations. The migration
 * runner has no down path and a failed `migrate()` is logged-not-fatal, so
 * this rolling backup (`app.db.pre-migrate.bak`) is the rollback story: a bad
 * migration is recovered by replacing the DB file with the backup. `VACUUM
 * INTO` writes a compact, consistent copy even mid-WAL. Best-effort — a backup
 * failure must never block startup.
 */
function backupBeforeMigrate(sqlite: Database.Database, migrationsFolder: string): void {
  try {
    const journal = JSON.parse(
      readFileSync(join(migrationsFolder, 'meta', '_journal.json'), 'utf8'),
    ) as { entries: unknown[] };
    const hasBookkeeping =
      (
        sqlite
          .prepare(
            "SELECT count(*) AS n FROM sqlite_master WHERE type = 'table' AND name = '__drizzle_migrations'",
          )
          .get() as { n: number }
      ).n > 0;
    let applied = 0;
    if (hasBookkeeping) {
      applied = (
        sqlite.prepare('SELECT count(*) AS n FROM "__drizzle_migrations"').get() as { n: number }
      ).n;
    } else {
      const userTables = (
        sqlite
          .prepare(
            "SELECT count(*) AS n FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'",
          )
          .get() as { n: number }
      ).n;
      if (userTables === 0) return; // brand-new DB — nothing to protect
    }
    if (journal.entries.length <= applied) return; // nothing pending

    const dest = `${paths.db()}.pre-migrate.bak`;
    if (existsSync(dest)) unlinkSync(dest);
    sqlite.prepare('VACUUM INTO ?').run(dest);
    log.info(`db: ${journal.entries.length - applied} migration(s) pending — backup written to ${dest}`);
  } catch (e) {
    log.warn('db: pre-migration backup failed (continuing)', e);
  }
}

export function initDb(): BetterSQLite3Database<typeof schema> {
  if (_db) return _db;

  mkdirSync(paths.userData(), { recursive: true });
  mkdirSync(paths.documents(), { recursive: true });
  mkdirSync(paths.vectors(), { recursive: true });

  const sqlite = new Database(paths.db());
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  _sqlite = sqlite;

  _db = drizzle(sqlite, { schema });

  const candidates = migrationCandidates();
  const migrationsFolder = candidates.find((dir) =>
    existsSync(join(dir, 'meta', '_journal.json')),
  );

  if (!migrationsFolder) {
    // Loud, actionable error: this means migrations weren't packaged correctly,
    // which leaves the DB without tables. Better to fail visibly than silently.
    log.error('db: migrations folder not found — tables will be missing. Looked in:', candidates);
  } else {
    backupBeforeMigrate(sqlite, migrationsFolder);
    try {
      migrate(_db, { migrationsFolder });
      log.info(`db: migrations applied from ${migrationsFolder}`);
    } catch (e) {
      log.error('db: migration failed', e);
    }
  }

  // Repair the FK actions migration 0001 created without ON DELETE clauses —
  // a table rebuild drizzle can't express (see fkRebuild.ts). A failure here
  // rolls back and the app keeps the legacy (pre-v1.5) delete behavior.
  try {
    fixLegacyFkActions(sqlite, log);
  } catch (e) {
    log.error('db: FK-action rebuild failed (continuing with legacy FK behavior)', e);
  }

  return _db;
}

export function db(): BetterSQLite3Database<typeof schema> {
  if (!_db) throw new Error('Database not initialized — call initDb() first');
  return _db;
}

/** Raw better-sqlite3 handle — for the DEV-only DB explorer. Do not use in app code. */
export function rawDb(): Database.Database {
  if (!_sqlite) throw new Error('Database not initialized — call initDb() first');
  return _sqlite;
}

export { schema };
