import { existsSync, mkdirSync } from 'fs';
import Database from 'better-sqlite3';
import { drizzle, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { join } from 'path';
import { app } from 'electron';
import { paths } from '../env';
import { log } from '../services/security/logger';
import * as schema from './schema';

let _db: BetterSQLite3Database<typeof schema> | null = null;
let _sqlite: Database.Database | null = null;

/**
 * Migrations are generated by drizzle-kit under ./drizzle. Depending on how the
 * app is packaged they can land in different spots, so we probe every plausible
 * location and use the first that actually contains the journal — far more robust
 * than assuming one path. In dev they sit at the repo root.
 */
function migrationCandidates(): string[] {
  if (!app.isPackaged) return [join(app.getAppPath(), 'drizzle')];
  return [
    join(process.resourcesPath, 'drizzle'), // extraResources (on disk) — preferred
    join(app.getAppPath(), 'drizzle'), // bundled in app.asar (files)
    join(__dirname, '../../drizzle'), // relative to out/main
  ];
}

export function initDb(): BetterSQLite3Database<typeof schema> {
  if (_db) return _db;

  mkdirSync(paths.userData(), { recursive: true });
  mkdirSync(paths.documents(), { recursive: true });
  mkdirSync(paths.vectors(), { recursive: true });

  const sqlite = new Database(paths.db());
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  _sqlite = sqlite;

  _db = drizzle(sqlite, { schema });

  const candidates = migrationCandidates();
  const migrationsFolder = candidates.find((dir) =>
    existsSync(join(dir, 'meta', '_journal.json')),
  );

  if (!migrationsFolder) {
    // Loud, actionable error: this means migrations weren't packaged correctly,
    // which leaves the DB without tables. Better to fail visibly than silently.
    log.error('db: migrations folder not found — tables will be missing. Looked in:', candidates);
  } else {
    try {
      migrate(_db, { migrationsFolder });
      log.info(`db: migrations applied from ${migrationsFolder}`);
    } catch (e) {
      log.error('db: migration failed', e);
    }
  }

  return _db;
}

export function db(): BetterSQLite3Database<typeof schema> {
  if (!_db) throw new Error('Database not initialized — call initDb() first');
  return _db;
}

/** Raw better-sqlite3 handle — for the DEV-only DB explorer. Do not use in app code. */
export function rawDb(): Database.Database {
  if (!_sqlite) throw new Error('Database not initialized — call initDb() first');
  return _sqlite;
}

export { schema };
