import { mkdirSync } from 'fs';
import Database from 'better-sqlite3';
import { drizzle, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { join } from 'path';
import { app } from 'electron';
import { paths } from '../env';
import { log } from '../services/security/logger';
import * as schema from './schema';

let _db: BetterSQLite3Database<typeof schema> | null = null;

export function initDb(): BetterSQLite3Database<typeof schema> {
  if (_db) return _db;

  mkdirSync(paths.userData(), { recursive: true });
  mkdirSync(paths.documents(), { recursive: true });
  mkdirSync(paths.vectors(), { recursive: true });

  const sqlite = new Database(paths.db());
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');

  _db = drizzle(sqlite, { schema });

  // Migrations are generated by drizzle-kit and bundled under ./drizzle.
  // In dev they sit at repo root; when packaged they are in the app resources.
  const migrationsFolder = app.isPackaged
    ? join(process.resourcesPath, 'drizzle')
    : join(app.getAppPath(), 'drizzle');

  try {
    migrate(_db, { migrationsFolder });
    log.info('db: migrations applied');
  } catch (e) {
    // First run before any migration files are generated should not crash dev.
    log.warn('db: migration step skipped/failed', e);
  }

  return _db;
}

export function db(): BetterSQLite3Database<typeof schema> {
  if (!_db) throw new Error('Database not initialized — call initDb() first');
  return _db;
}

export { schema };
